<a href="https://colab.research.google.com/github/rajucherry03/Python-For-Data-Science/blob/main/Exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Practice Indexing
import numpy as np
arr=np.array([1,2,3,4,5,6])
b=arr[2]
print(b)
print(arr[2])

3
3


In [ ]:
#Slice
import numpy as np
arr=np.array([1,2,10,20,3,4,7,9,10])
print(arr[2:5])

[10 20  3]


In [ ]:
#Reshaping
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,45,10,2])
newarr=arr.reshape(4,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 45 10  2]]


In [ ]:
#Joining
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7])
newarr=np.concatenate((arr1,arr2))
print(newarr)

[1 2 3 4 5 6 7]


In [ ]:
#Splitting
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
