<a href="https://colab.research.google.com/github/rajucherry03/Python-For-Data-Science/blob/main/Exp6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Standard Deviation
import numpy as np
a=np.array([5,6,7])
print(a)
print(np.std(a))

[5 6 7]
0.816496580927726


In [4]:
#Varience
a=np.array([[1,2],[3,4]])
print(a)
print(np.var(a))

[[1 2]
 [3 4]]
1.25


In [5]:
#Median
a=np.array([1,2,3])
print(a)
print(np.median(a))

[1 2 3]
2.0


In [8]:
#Mode
from scipy import stats as st
a=np.array([1,2,3,3,3,4])
print(a)
print(st.mode(a))

[1 2 3 3 3 4]
ModeResult(mode=array([3]), count=array([3]))


<ipython-input-8-33c0460322a8>:5: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(st.mode(a))


In [9]:
#Mean 
a=np.array([5,6,7])
print(a)
b=np.mean(a)
print(b)

[5 6 7]
6.0


**Applying Statistical Function on csv**

In [10]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [11]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Student_Marks.csv')
df.head()

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [12]:
#Mean
import pandas as pd
mean1 = df['Marks'].mean()
print(mean1)

24.417689999999997


In [13]:
#Median
import pandas as pd
median1 = df['Marks'].median()
print(median1)

20.0595


In [14]:
#Standard deviation
import pandas as pd
std1 = df['Marks'].std()
print(std1)

14.326198570757976


In [15]:
#Varience
import pandas as pd
var1 = df['Marks'].var()
print(var1)

205.23996548878785


In [18]:
#Mode
import pandas as pd
mode1 = df['number_courses'].mode()
print(mode1)

0    3
Name: number_courses, dtype: int64
