<a href="https://colab.research.google.com/github/rajucherry03/Python-For-Data-Science/blob/main/Exp6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Standard Deviation
import numpy as np
a=np.array([5,6,7])
print(a)
print(np.std(a))

[5 6 7]
0.816496580927726


In [ ]:
#Varience
a=np.array([[1,2],[3,4]])
print(a)
print(np.var(a))

[[1 2]
 [3 4]]
1.25


In [ ]:
#Median
a=np.array([1,2,3])
print(a)
print(np.median(a))

[1 2 3]
2.0


In [ ]:
#Mode
from scipy import stats as st
a=np.array([1,2,3,3,3,4])
print(a)
print(st.mode(a))

[1 2 3 3 3 4]
ModeResult(mode=array([3]), count=array([3]))


<ipython-input-8-33c0460322a8>:5: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(st.mode(a))


In [ ]:
#Mean 
a=np.array([5,6,7])
print(a)
b=np.mean(a)
print(b)

[5 6 7]
6.0


**Applying Statistical Function on csv**

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [20]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/1-Pds Lab/sales_team.csv')
df.head()

Customer Number     Customer Name         2016          2017  \
0          10002.0  Quest Industries  $125,000.00    $162500.00   
1         552278.0    Smith Plumbing  $920,000.00  $101,2000.00   
2          23477.0   ACME Industrial   $50,000.00     $62500.00   
3          24900.0        Brekke LTD  $350,000.00    $490000.00   
4         651029.0         Harbor Co   $15,000.00     $12750.00   

  Percent Growth Jan Units  Month  Day  Year Active  
0         30.00%       500      1   10  2015      Y  
1         10.00%       700      6   15  2014      Y  
2         25.00%       125      3   29  2016      Y  
3          4.00%        75     10   27  2015      Y  
4        -15.00%    Closed      2    2  2014      N

In [28]:
df['2016']+df['2017']

0      $125,000.00$162500.00
1    $920,000.00$101,2000.00
2        $50,000.00$62500.00
3      $350,000.00$490000.00
4        $15,000.00$12750.00
dtype: object

In [29]:
df['Day']+df['Month']

0    11
1    21
2    32
3    37
4     4
dtype: int64

In [31]:
df.dtypes

Customer Number    float64
Customer Name       object
2016                object
2017                object
Percent Growth      object
Jan Units           object
Month                int64
Day                  int64
Year                 int64
Active              object
dtype: object

In [32]:
df.columns

Index(['Customer Number', 'Customer Name', '2016', '2017', 'Percent Growth',
       'Jan Units', 'Month', 'Day', 'Year', 'Active'],
      dtype='object')

In [34]:
df.describe()

Customer Number      Month        Day        Year
count         5.000000   5.000000   5.000000     5.00000
mean     252337.200000   4.400000  16.600000  2014.80000
std      320838.999788   3.646917  11.414903     0.83666
min       10002.000000   1.000000   2.000000  2014.00000
25%       23477.000000   2.000000  10.000000  2014.00000
50%       24900.000000   3.000000  15.000000  2015.00000
75%      552278.000000   6.000000  27.000000  2015.00000
max      651029.000000  10.000000  29.000000  2016.00000

In [35]:
df.head()


Customer Number     Customer Name         2016          2017  \
0          10002.0  Quest Industries  $125,000.00    $162500.00   
1         552278.0    Smith Plumbing  $920,000.00  $101,2000.00   
2          23477.0   ACME Industrial   $50,000.00     $62500.00   
3          24900.0        Brekke LTD  $350,000.00    $490000.00   
4         651029.0         Harbor Co   $15,000.00     $12750.00   

  Percent Growth Jan Units  Month  Day  Year Active  
0         30.00%       500      1   10  2015      Y  
1         10.00%       700      6   15  2014      Y  
2         25.00%       125      3   29  2016      Y  
3          4.00%        75     10   27  2015      Y  
4        -15.00%    Closed      2    2  2014      N

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Customer Number  5 non-null      float64
 1   Customer Name    5 non-null      object 
 2   2016             5 non-null      object 
 3   2017             5 non-null      object 
 4   Percent Growth   5 non-null      object 
 5   Jan Units        5 non-null      object 
 6   Month            5 non-null      int64  
 7   Day              5 non-null      int64  
 8   Year             5 non-null      int64  
 9   Active           5 non-null      object 
dtypes: float64(1), int64(3), object(6)
memory usage: 528.0+ bytes


In [38]:
df['Customer Number'].astype('int')

0     10002
1    552278
2     23477
3     24900
4    651029
Name: Customer Number, dtype: int64

In [40]:
df['Customer Number'].astype('int')

0     10002
1    552278
2     23477
3     24900
4    651029
Name: Customer Number, dtype: int64

In [45]:
def conver_currency(val):
  newval=val.replace(',','').replace('$','')
  return float(newval)
df['2016']=df['2016'].apply(conver_currency)

In [ ]:
df['2016']=df['2016'].apply(conver_currency)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Customer Number  5 non-null      float64
 1   Customer Name    5 non-null      object 
 2   2016             5 non-null      float64
 3   2017             5 non-null      object 
 4   Percent Growth   5 non-null      object 
 5   Jan Units        5 non-null      object 
 6   Month            5 non-null      int64  
 7   Day              5 non-null      int64  
 8   Year             5 non-null      int64  
 9   Active           5 non-null      object 
dtypes: float64(2), int64(3), object(5)
memory usage: 528.0+ bytes


In [22]:
#Mean
import pandas as pd
mean1 = df['Month'].mean()
print(mean1)

4.4


In [23]:
#Median
import pandas as pd
median1 = df['Month'].median()
print(median1)

3.0


In [24]:
#Standard deviation
import pandas as pd
std1 = df['Month'].std()
print(std1)

3.646916505762094


In [25]:
#Varience
import pandas as pd
var1 = df['Month'].var()
print(var1)

13.3


In [26]:
#Mode
import pandas as pd
mode1 = df['Month'].mode()
print(mode1)

0     1
1     2
2     3
3     6
4    10
Name: Month, dtype: int64
