<a href="https://colab.research.google.com/github/rajucherry03/Python-For-Data-Science/blob/main/Exp6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Standard Deviation
import numpy as np
a=np.array([5,6,7])
print(a)
print(np.std(a))

[5 6 7]
0.816496580927726


In [4]:
#Varience
a=np.array([[1,2],[3,4]])
print(a)
print(np.var(a))

[[1 2]
 [3 4]]
1.25


In [5]:
#Median
a=np.array([1,2,3])
print(a)
print(np.median(a))

[1 2 3]
2.0


In [8]:
#Mode
from scipy import stats as st
a=np.array([1,2,3,3,3,4])
print(a)
print(st.mode(a))

[1 2 3 3 3 4]
ModeResult(mode=array([3]), count=array([3]))


<ipython-input-8-33c0460322a8>:5: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(st.mode(a))


In [9]:
#Mean 
a=np.array([5,6,7])
print(a)
b=np.mean(a)
print(b)

[5 6 7]
6.0


**Applying Statistical Function on csv**