<a href="https://colab.research.google.com/github/rajucherry03/Python-For-Data-Science/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Zeros create a 2d m ele of zeros and same as for other numbers
import numpy as np
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#arange it prints the num from 0 to n-1 place sequentially
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#linspace 
import numpy as np
np.linspace(1,26,3)

array([ 1. , 13.5, 26. ])

In [ ]:
#Indices 
import numpy as np
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
#Indices 
import numpy as np
np.indices((4,4))

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [ ]:
import numpy as np
np.random.rand(3,2)

array([[0.05359127, 0.75614524],
       [0.95530787, 0.14362585],
       [0.41595816, 0.30433616]])

In [ ]:
import numpy as np
np.random.rand(3,2)

array([[0.92628767, 0.74579073],
       [0.93000819, 0.99628155],
       [0.52706091, 0.95934612]])

In [ ]:
import numpy as np
x=np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
import numpy as np
np.random.randint(10,size=10)

array([3, 2, 9, 1, 1, 4, 2, 9, 2, 4])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.add(a,b)
print(c)

[2 4 6]


In [ ]:
import numpy as np
a=np.array([1,2,3,5,8,9])
print("Actual num: ")
print(a)
print("After rev")
c=np.flip(a)
print(c)

Actual num: 
[1 2 3 5 8 9]
After rev
[9 8 5 3 2 1]


In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("3*3 matrix")
print(matrix)
column = np.column_stack((matrix, np.zeros(3)))
row = np.vstack((column, np.ones(4)))
print("After adding column and row: ")
print(row)


3*3 matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After adding column and row: 
[[1. 2. 3. 0.]
 [4. 5. 6. 0.]
 [7. 8. 9. 0.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 1, 4, 5])
matchingindices = np.where(arr1 == arr2)
print(matchingindices)


(array([3, 4]),)


In [ ]:
import numpy as np

rand_arr = np.random.uniform(low=0, high=10, size=10)

rounded_arr = np.round(rand_arr)
print("Original Array: ", rand_arr)
print("Rounded Array: ", rounded_arr)


Original Array:  [8.28552139 1.79272382 2.25892564 2.7006616  5.99760257 2.31867878
 6.14991812 0.46265516 4.03418371 5.40687669]
Rounded Array:  [8. 2. 2. 3. 6. 2. 6. 0. 4. 5.]
